# This is a basic workflow to help you get started with Actions

name: Deploy to master

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]


permissions:
  contents: read
  id-token: write


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Environment variables
        uses: actions/checkout@v3

      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/991876403952/locations/global/workloadIdentityPools/deploy-function/providers/github-deploy-function
          service_account: cloud-function-deploy-375513@appspot.gserviceaccount.com

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Build
        run: ./gradlew :cloud-function-deploy:build

      - name: Prep
        run: |
          mkdir deploy
          cp cloud-function-deploy/build/libs/shadow-all.jar deploy/

      - id: deploy-httpFunction
        uses: google-github-actions/deploy-cloud-functions@v0
        with:
          name: httpFunction
          runtime: java11
          entry_point: com.example.httpdeploy.App
          source_dir: deploy

